### ISSUE TITLE
Adressensuche bricht ab

### ISSUE THREAD

**Issue by ro3t** [bfpi/klarschiff-frontend2#18]
Eine Adresssuche nach dem Ernst-Thälmann-Ring liefert ab dem ersten Bindestrich keine Ergebnisse mehr. Gleiches gilt bei Leerzeichen (Bsp.: "Ernst Th")

**Comment by alexkuebo** [comment]
Antwort der Wheregroup:
> das ist so beabsichtigt gewesen. Wir gehen davon aus das Benutzer wenn Sie nach Thälmann suchen nicht bei T aufhören zu tippen. Die Eingabe wird an Sonderzeichen gesplittet und anschließend trunkiert vorausgesetzt es handelt sich dabei um mehr als nur zwei Zeichen. Ansonsten würde mal auch Hausnummerzusätze trunkieren. Sollte dieses Verhalten nicht erwünscht sein, so kann man einfach in der Datei "Search.php" in Zeile 112 folgendes verändern.
> 
> https://github.com/bfpi/klarschiff-frontend/blob/erweiterung-adressen/frontend-desktop/http/pc/search/Search.php#L112
> 
> Von:
> 
> if (preg_match("/^[\d]+$/", $term) || strlen($term) <= 2) {
> 
> in:
> 
> if (preg_match("/^[\d]+$/", $term)) {
